groups:
- name: alerts
  rules:
  - alert: EndpointDown
    expr: sum by (instance) (probe_success) == 0
    for: 10s
    labels:
      severity: "critical"
    annotations:
      summary: "Endpoint Down"  
      description: "Endpoint Down  {{ $labels.module }} {{ $labels.instance }} desc"
  - alert: AlertManagerDown
    expr: prometheus_notifications_errors_total > 0
    for: 50s
    labels:
      severity: "critical"
    annotations:
      summary: "Alert Manager Down"  
      description: "{{ $labels.module }} {{ $labels.alertmanager }}" 
  - alert: ThanosComponentDown
    expr: thanos_status == 0
    for: 30s
    labels:
      severity: "critical"
    annotations:
      summary: "Thanos {{ $labels.module }} Down"  
      description: "{{ $labels.module }} {{ $labels.alertmanager }}"  


