global:
  smtp_smarthost: { { smtp_smarthost } }
  smtp_from: { { smtp_from } }
  smtp_require_tls: true

templates:
  - "/etc/carbonio/carbonio-prometheus-alertmanager/*.tmpl"

route:
  group_by: ["alertname", "job", "istance"]
  repeat_interval: 1m
  group_interval: 2m
  receiver: "default"
  routes:
    - match:
        severity: warning
      receiver: warning

    - match:
        severity: critical
      receiver: critical

receivers:
  - name: "default"
    email_configs:
      - send_resolved: false
        to: { { smtp_to } }
        headers:
          subject: "{{ .Alerts.Firing | len }} {{ .CommonLabels.severity }} alert on {{ .CommonLabels.instance }}"
        html: '{{ template "email.tmpl" . }}'
        require_tls: false
  - name: "warning"
    email_configs:
      - send_resolved: false
        to: { { smtp_to } }
        headers:
          subject: "{{ .Alerts.Firing | len }} {{ .CommonLabels.severity }} alert on {{ .CommonLabels.instance }}"
        html: '{{ template "email.tmpl" . }}'
        require_tls: false
  - name: "critical"
    email_configs:
      - send_resolved: false
        to: { { smtp_to } }
        headers:
          subject: "{{ .Alerts.Firing | len }} {{ .CommonLabels.severity }} alert on {{ .CommonLabels.instance }}"
        html: '{{ template "email.tmpl" . }}'
        require_tls: false
